apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.Values.name}}
  name: {{.Values.name}}
spec:
  ports:
  - port: {{.Values.port}}
  selector:
    name: {{.Values.name}}
  type: LoadBalancer
